# -*- coding: utf-8 -*-
"""kaggle_PIA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jHf5OmtezaCrGc8L1Jr5aBhQzPDrNjzt
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from sklearn.model_selection import train_test_split
from tensorflow.keras import datasets, layers, models

import glob
from PIL import Image
from skimage.color import rgb2gray
from tensorflow import keras

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.environ['KAGGLE_CONFIG_DIR'] = '/content/gdrive/MyDrive/IA_PIA'

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/MyDrive/IA_PIA

!ls

!kaggle datasets download -d andrewmvd/medical-mnist

!mkdir Imagenes_Pia
!mv medical-mnist.zip Imagenes_Pia

# Commented out IPython magic to ensure Python compatibility.
# %cd Imagenes_Pia/

!unzip medical-mnist.zip

import cv2
from google.colab.patches import cv2_imshow
img = cv2.imread('/content/gdrive/MyDrive/IA_PIA/Imagenes_Pia/CXR/000003.jpeg')
cv2_imshow(img)

folder_abdomen = '/Imagenes_PIA/AbdomenCT'
folder_breast = '/Imagenes_PIA/BreastMRI'
folder_cxr = '/Imagenes_PIA/CXR'
folder_chest = '/Imagenes_PIA/ChestCT'
folder_hand = '/Imagenes_PIA/Hand'
folder_head = '/Imagenes_PIA/HeadCT'

image_files_abdomen = glob.glob(folder_abdomen + '/*.jpg')
image_files_breast = glob.glob(folder_breast + '/*.jpg')
image_files_cxr = glob.glob(folder_cxr + '/*.jpg')
image_files_chest = glob.glob(folder_chest + '/*.jpg')
image_files_hand = glob.glob(folder_hand + '/*.jpg')
image_files_head = glob.glob(folder_head + '/*.jpg')

images_abdomen = []
labels_abdomen = []

images_breast = []
labels_breast = []

images_cxr = []
labels_cxr = []

images_chest = []
images_chest = []

images_hand = []
images_hand = []

images_head = []
images_head = []

class_names = ['abdomen', 'breast', 'cxr', 'chest', 'hand', 'head']

for image_file in image_files_abdomen:
    image = Image.open(image_file)
    images_abdomen.append(image)
    labels_abdomen.append("abdomen")

plt.imshow(images_abdomen[0])
plt.show()